### ISSUE TITLE
Warn the user if Save button is pressed when editor is empty

### ISSUE THREAD

**Issue by cclauss** [jsbain/EditAreaForPythonista#4]

**Comment by jsbain** [comment]
I'm not sure if there is an easy way to have the js editor callback when text is changed.  I guess the easiest way to do this would be to allow save button to still be pressed, I.e not disable in the ui, but warn if empty.  

As for the filename box, my eventual goal is to remove that.  Open should pop up a selection dialog.  Save would save.  Would add a saveas to allow renaming, which would proper to overwrite existing.
Actually, my real eventual goal is to get rid of the ui buttons, and use the javascript buttons, using a custom url scheme and a webview delegate to let the python handle javascript callbacks.
